version: '3.4'

services:
  catalogdb:
    image: mongo

  #catalog.api:
  #  image: ${DOCKER_REGISTRY-}catalogapi
  #  build:
  #    context: .
  #    dockerfile: Services/Catalog/Catalog.API/Dockerfile

  #identdb:
  #  image: postgres

  #basketdb:
  #  image: redis:alpine

  #basket.api:
  #  image: ${DOCKER_REGISTRY-}basketapi
  #  build:
  #    context: .
  #    dockerfile: Services/Basket/Basket.API/Dockerfile

  #ident.server:
  #  image: ${DOCKER_REGISTRY-}identserver
  #  build:
  #    context: .
  #    dockerfile: Ident/EsparkIndent.Server/Dockerfile

  #ocelotapigw:
  #  image: ${DOCKER_REGISTRY-}ocelotapigw
  #  build:
  #    context: .
  #    dockerfile: ApiGateways/OcelotApiGw/OcelotApiGw/Dockerfile
  
  #rabbitmq:
  #  image: rabbitmq:3-management-alpine



volumes:
  mongo_data:
  postgres_data:
  



