version: '3.4'

services:
  catalogdb:
    image: mongo

  identdb:
    image: postgres
   
  orderdbs:
    image: postgres

  basketdb:
    image: redis:alpine

  ident.server:
    image: ${DOCKER_REGISTRY-}identserver
    build:
      context: .
      dockerfile: Ident/EsparkIndent.Server/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  #ocelotapigw:
  #  image: ${DOCKER_REGISTRY-}ocelotapigw
  #  build:
  #    context: .
  #    dockerfile: ApiGateways/OcelotApiGw/OcelotApiGw/Dockerfile
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  #shoppingaggregator:
  #  image: ${DOCKER_REGISTRY-}shoppingaggregator
  #  build:
  #    context: .
  #    dockerfile: ApiGateways/ShoppingAggregator/Dockerfile

volumes:
  mongo_data:
  postgres_data_order:
  postgres_data_ident:
  redis_data:






